#!/bin/sh
chkroot(){
	if [ "$(id -u)" != "0" ]; then
	  echo "E: root access required."
	  exit 1
	fi
}
chkroot
if cp  php2html /usr/bin/; then
    echo "Successfully installed in /usr/bin/php2html"
elif cp php2html /usr/local/bin/; then
    echo "Successfully installed in /usr/local/bin/php2html"
else
    echo "FAILED!!! Make sure you are running this script from the package directory."
fi

